/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.maple.frontend.eventManagerScreen;

import com.maple.backend.model.User;
import com.maple.frontend.HomeJPanel;
import com.maple.frontend.HomeLeftJPanel;
import java.util.ArrayList;
import javax.swing.JSplitPane;

/**
 *
 * @author DKapoor
 */
public class EventManagerScreen extends javax.swing.JPanel {

    /**
     * Creates new form EventManagerScreen
     */
    JSplitPane mainSplitPane;
    ArrayList<User> userData;
    public EventManagerScreen(JSplitPane jSplitPane) {
        initComponents();
        this.mainSplitPane = jSplitPane;
//        this.userData = userData;
        
//        EventManagerDashboard eventManagerDashboard = new EventManagerDashboard(userData);
//        jRightSplitPane.setRightComponent(eventManagerDashboard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBaseSplitPane = new javax.swing.JSplitPane();
        jBaseLeftPanel = new javax.swing.JPanel();
        mapleLogo = new com.maple.resources.ImageAvatar();
        jLogoutBtn = new com.maple.resources.Button();
        jDashboardBtn = new com.maple.resources.Button();
        jRequestsBtn = new com.maple.resources.Button();
        jBaseRightPanel = new javax.swing.JPanel();
        jTopSplitPane = new javax.swing.JSplitPane();
        jRightTopPanel = new javax.swing.JPanel();
        burgerBadge = new com.maple.resources.ButtonBadges();
        messageBadge = new com.maple.resources.ButtonBadges();
        notificationBadge = new com.maple.resources.ButtonBadges();
        jUserName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jUserRole = new javax.swing.JLabel();
        jUserImageIcon = new com.maple.resources.ImageAvatar();
        jRightBottomPanel = new javax.swing.JPanel();

        jBaseSplitPane.setDividerSize(0);
        jBaseSplitPane.setMaximumSize(new java.awt.Dimension(1100, 800));
        jBaseSplitPane.setMinimumSize(new java.awt.Dimension(1100, 800));
        jBaseSplitPane.setPreferredSize(new java.awt.Dimension(1100, 800));

        jBaseLeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        jBaseLeftPanel.setMaximumSize(new java.awt.Dimension(128, 812));
        jBaseLeftPanel.setMinimumSize(new java.awt.Dimension(128, 812));
        jBaseLeftPanel.setPreferredSize(new java.awt.Dimension(128, 812));

        mapleLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maple/icons/maple.png"))); // NOI18N

        jLogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maple/icons/logout.png"))); // NOI18N
        jLogoutBtn.setText("Logout");
        jLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutBtnActionPerformed(evt);
            }
        });

        jDashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maple/icons/dash.png"))); // NOI18N
        jDashboardBtn.setText("Dashboard");
        jDashboardBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maple/icons/1.png"))); // NOI18N
        jDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDashboardBtnActionPerformed(evt);
            }
        });

        jRequestsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maple/icons/analytics.png"))); // NOI18N
        jRequestsBtn.setText("Requests");
        jRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRequestsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBaseLeftPanelLayout = new javax.swing.GroupLayout(jBaseLeftPanel);
        jBaseLeftPanel.setLayout(jBaseLeftPanelLayout);
        jBaseLeftPanelLayout.setHorizontalGroup(
            jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBaseLeftPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mapleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                        .addGroup(jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jBaseLeftPanelLayout.setVerticalGroup(
            jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                .addComponent(jLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jBaseSplitPane.setLeftComponent(jBaseLeftPanel);

        jTopSplitPane.setDividerSize(0);
        jTopSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jTopSplitPane.setMaximumSize(new java.awt.Dimension(985, 880));
        jTopSplitPane.setMinimumSize(new java.awt.Dimension(985, 880));
        jTopSplitPane.setPreferredSize(new java.awt.Dimension(985, 880));

        jRightTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        jRightTopPanel.setMaximumSize(new java.awt.Dimension(985, 80));
        jRightTopPanel.setMinimumSize(new java.awt.Dimension(985, 80));
        jRightTopPanel.setPreferredSize(new java.awt.Dimension(985, 80));

        burgerBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maple/icons/menu.png"))); // NOI18N

        messageBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maple/icons/message.png"))); // NOI18N

        notificationBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maple/icons/notification.png"))); // NOI18N
        notificationBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBadgeActionPerformed(evt);
            }
        });

        jUserName.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jUserName.setForeground(new java.awt.Color(127, 127, 127));
        jUserName.setText("User Name");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jUserRole.setForeground(new java.awt.Color(127, 127, 127));
        jUserRole.setText("Event Manager");

        javax.swing.GroupLayout jRightTopPanelLayout = new javax.swing.GroupLayout(jRightTopPanel);
        jRightTopPanel.setLayout(jRightTopPanelLayout);
        jRightTopPanelLayout.setHorizontalGroup(
            jRightTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRightTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(burgerBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 636, Short.MAX_VALUE)
                .addComponent(messageBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jRightTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jUserName)
                    .addComponent(jUserRole))
                .addGap(18, 18, 18)
                .addComponent(jUserImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jRightTopPanelLayout.setVerticalGroup(
            jRightTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRightTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jRightTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRightTopPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jRightTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notificationBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(burgerBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jRightTopPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jRightTopPanelLayout.createSequentialGroup()
                        .addGroup(jRightTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jRightTopPanelLayout.createSequentialGroup()
                                .addComponent(jUserName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jUserRole))
                            .addComponent(jUserImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTopSplitPane.setTopComponent(jRightTopPanel);

        jRightBottomPanel.setMaximumSize(new java.awt.Dimension(1100, 800));
        jRightBottomPanel.setMinimumSize(new java.awt.Dimension(1100, 800));
        jRightBottomPanel.setPreferredSize(new java.awt.Dimension(1100, 800));

        javax.swing.GroupLayout jRightBottomPanelLayout = new javax.swing.GroupLayout(jRightBottomPanel);
        jRightBottomPanel.setLayout(jRightBottomPanelLayout);
        jRightBottomPanelLayout.setHorizontalGroup(
            jRightBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jRightBottomPanelLayout.setVerticalGroup(
            jRightBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jTopSplitPane.setRightComponent(jRightBottomPanel);

        javax.swing.GroupLayout jBaseRightPanelLayout = new javax.swing.GroupLayout(jBaseRightPanel);
        jBaseRightPanel.setLayout(jBaseRightPanelLayout);
        jBaseRightPanelLayout.setHorizontalGroup(
            jBaseRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jBaseRightPanelLayout.setVerticalGroup(
            jBaseRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jBaseSplitPane.setRightComponent(jBaseRightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBaseSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBaseSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutBtnActionPerformed
        //Reset right panel
        HomeJPanel homeScreen = new HomeJPanel(this.mainSplitPane);
        this.mainSplitPane.setRightComponent(homeScreen);
        //Reset left panel
        HomeLeftJPanel homeLeftPanel = new HomeLeftJPanel(this.mainSplitPane);
        this.mainSplitPane.setLeftComponent(homeLeftPanel);
    }//GEN-LAST:event_jLogoutBtnActionPerformed

    private void jDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDashboardBtnActionPerformed
            EventManagerDashboard eventManagerDashboard = new EventManagerDashboard(userData);
            jBaseSplitPane.setBottomComponent(eventManagerDashboard);
       
    }//GEN-LAST:event_jDashboardBtnActionPerformed

    private void notificationBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBadgeActionPerformed
//        try {
//            notificationBadge.setBadges(0);
//            BusinessAdminRequest businessAdminRequest = new BusinessAdminRequest(userData);
//            jRightSplitPane.setBottomComponent(businessAdminRequest);
//        } catch (SQLException ex) {}
    }//GEN-LAST:event_notificationBadgeActionPerformed

    private void jRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRequestsBtnActionPerformed
    
            EventManagerRequests eventManagerRequests = new EventManagerRequests(userData);
            jBaseSplitPane.setBottomComponent(eventManagerRequests);
        
    }//GEN-LAST:event_jRequestsBtnActionPerformed
public JSplitPane getBaseSplitPane(){
        return this.jBaseSplitPane;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.maple.resources.ButtonBadges burgerBadge;
    private javax.swing.JPanel jBaseLeftPanel;
    private javax.swing.JPanel jBaseRightPanel;
    private javax.swing.JSplitPane jBaseSplitPane;
    private com.maple.resources.Button jDashboardBtn;
    private com.maple.resources.Button jLogoutBtn;
    private com.maple.resources.Button jRequestsBtn;
    private javax.swing.JPanel jRightBottomPanel;
    private javax.swing.JPanel jRightTopPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jTopSplitPane;
    private com.maple.resources.ImageAvatar jUserImageIcon;
    private javax.swing.JLabel jUserName;
    private javax.swing.JLabel jUserRole;
    private com.maple.resources.ImageAvatar mapleLogo;
    private com.maple.resources.ButtonBadges messageBadge;
    private com.maple.resources.ButtonBadges notificationBadge;
    // End of variables declaration//GEN-END:variables
}
