/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.maple.frontend;
import com.maple.backend.controller.EnterpriseController;
import com.maple.backend.controller.UserController;
import com.maple.backend.model.User;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.maple.backend.controller.WorkRequestController;
import com.maple.backend.model.Catering;
import com.maple.backend.model.Hotel;
import com.maple.backend.model.TravelAgent;
import com.maple.backend.model.WorkRequest;
import com.maple.backend.service.EventService;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSplitPane;

/**
 *
 * @author DKapoor
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    JSplitPane mainSplitPane;
    String path;
    WorkRequestController workRequestController;
    User user;
    UserController userController;
    
    EnterpriseController enterpriseController;
    
    public RegisterJPanel(JSplitPane jSplitPane) throws SQLException {
        initComponents();
        this.mainSplitPane = jSplitPane;
        user = new User();
        userController = new UserController();
        workRequestController = new WorkRequestController();
        enterpriseController = new EnterpriseController();
        
        disableAdditionalFields();
        
    }
    
    private void disableAdditionalFields(){
       
        //disable additional data
        jAddressLabel.setVisible(false);
        jAddress.setVisible(false);
        jCapacityLabel.setVisible(false);
        jCapacity.setVisible(false);
        jTypeLabel.setVisible(false);
        jType.setVisible(false);
        jArea.setVisible(false);
        jAreaLabel.setVisible(false);
        jCompanyNameLabel.setVisible(false);
        jCompanyName.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPhotoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRegisterAsComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPostalCodeTextField = new com.maple.resources.TextField();
        jNameTextField = new com.maple.resources.TextField();
        jEmailTextField = new com.maple.resources.TextField();
        jPhoneNumberTextField = new com.maple.resources.TextField();
        jUsernameTextField = new com.maple.resources.TextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordTextField = new com.maple.resources.TextField();
        jConfirmPasswordTextField = new com.maple.resources.TextField();
        jLabel14 = new javax.swing.JLabel();
        jUploadBtn = new com.maple.resources.Button();
        jAddressLabel = new javax.swing.JLabel();
        jAreaLabel = new javax.swing.JLabel();
        jCompanyNameLabel = new javax.swing.JLabel();
        jTypeLabel = new javax.swing.JLabel();
        jCapacityLabel = new javax.swing.JLabel();
        jType = new com.maple.resources.TextField();
        jAddress = new com.maple.resources.TextField();
        jArea = new com.maple.resources.TextField();
        jCapacity = new com.maple.resources.TextField();
        jCompanyName = new com.maple.resources.TextField();
        jRegisterBtn = new com.maple.resources.Button();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Maple Management System");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register");

        jRegisterAsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Hotel Admin", "Catering Admin", "Travel Agent Admin" }));
        jRegisterAsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterAsComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("Register as");

        jLabel11.setText("Photo");

        jPostalCodeTextField.setLabelText("");

        jNameTextField.setLabelText("");

        jEmailTextField.setLabelText("");

        jPhoneNumberTextField.setLabelText("");

        jUsernameTextField.setLabelText("");

        jLabel6.setText("Name");

        jLabel7.setText("Email");

        jLabel8.setText("Phone Number");

        jLabel9.setText("Username");

        jLabel12.setText("Password");

        jLabel13.setText("Postal Code");

        jPasswordTextField.setLabelText("");

        jConfirmPasswordTextField.setLabelText("");

        jLabel14.setText("Confirm Password");

        jUploadBtn.setText("Upload");
        jUploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUploadBtnActionPerformed(evt);
            }
        });

        jAddressLabel.setText("Address");

        jAreaLabel.setText("Area");

        jCompanyNameLabel.setText("Company name");

        jTypeLabel.setText("Type");

        jCapacityLabel.setText("Capacity");

        jType.setLabelText("");

        jAddress.setLabelText("");

        jArea.setLabelText("");

        jCapacity.setLabelText("");

        jCompanyName.setLabelText("");

        jRegisterBtn.setText("Register");
        jRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jUploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRegisterAsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPhoneNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jUsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jConfirmPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jPostalCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAddressLabel)
                                    .addComponent(jAreaLabel)
                                    .addComponent(jCompanyNameLabel)
                                    .addComponent(jTypeLabel)
                                    .addComponent(jCapacityLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jArea, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRegisterAsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddressLabel)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jAreaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jCompanyNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jCapacityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPostalCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jUploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(30, 30, 30)
                                .addComponent(jRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
//        String role = jRegisterAsComboBox.getSelectedIndex(selectedHospitalAdmin.getGender());

        
        
    }                                               

    private void jRegisterAsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterAsComboBoxActionPerformed
        // TODO add your handling code here:
        String role = jRegisterAsComboBox.getSelectedItem().toString();
        if(!role.equalsIgnoreCase("Customer")){
            jAddressLabel.setVisible(true);
            jAddress.setVisible(true);
            jCapacityLabel.setVisible(true);
            jCapacity.setVisible(true);
            jTypeLabel.setVisible(true);
            jType.setVisible(true);
            jArea.setVisible(true);
            jAreaLabel.setVisible(true);
            jCompanyNameLabel.setVisible(true);
            jCompanyName.setVisible(true);
            return;
        }
        disableAdditionalFields();
       
    }//GEN-LAST:event_jRegisterAsComboBoxActionPerformed

    private void jUploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUploadBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser img_upload = new JFileChooser();
        img_upload.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = img_upload.showDialog(null, "Choose my file");
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = img_upload.getSelectedFile();
            String path = file.getAbsolutePath().replace("\\", "\\\\");
            this.path = path;
            try {
                Image photo = ImageIO.read(file).getScaledInstance(65, 105, 65);
//                user.setPhoto(photo);
                jPhotoLabel.setIcon(new ImageIcon(photo));
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error while saving image.");
            }
        }
        else{
                JOptionPane.showMessageDialog(this, "Upload is cancelled.");
            }
    }//GEN-LAST:event_jUploadBtnActionPerformed

    private void jRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterBtnActionPerformed
        // TODO add your handling code here:
        String role = jRegisterAsComboBox.getSelectedItem().toString();
        String name = jNameTextField.getText();
        String email = jEmailTextField.getText();
        String phoneNum = jPhoneNumberTextField.getText();
        String userName = jUsernameTextField.getText();
        String password = jPasswordTextField.getText();
        String rePassword = jConfirmPasswordTextField.getText();
        String postalCode = jPostalCodeTextField.getText();
        String address = "";
        String area = "";
        String capacity = "";
        String type = "";
        String companyName = "";
        
        //TODO: pass these too
        if(!role.equalsIgnoreCase("CUSTOMER")){
            address = jAddress.getText();
            area = jArea.getText();
            capacity = jCapacity.getText();
            type = jType.getText();
            companyName = jCompanyName.getText();
        }
        
        if (role.equals("")){
            JOptionPane.showMessageDialog(this, "Please select a valid role to register.");
        }
        else if (name.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your name.");
        }
        else if (email.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your email id.");
        }
        else if (phoneNum.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your phone number.");
        } else if (userName.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a username.");
        } else if (password.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a password.");
        } else if (rePassword.equals("")){
            JOptionPane.showMessageDialog(this, "Please re-enter the password.");
        } else if (!rePassword.equals(password)){
            JOptionPane.showMessageDialog(this, "Your passwords do not match.");
        } else if (path.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a photo.");
        } else{
            try {
                String status = "PENDING" ;
                if ("customer".equals(role)){
                    status = "active";
                }
                
            int ID = userController.getAllUsers();

            
            //insert in USER table
            userController.insertUserDataController(ID, role, name, email, phoneNum, userName, password, path, postalCode, status);

            if(role.equalsIgnoreCase("HOTEL ADMIN")){
                //insert in HCT table
                Hotel hotelData = new Hotel();
                hotelData.setHotelID(enterpriseController.getAllHotelData().size()+1); //TODO: generate
                hotelData.setHotelName(companyName);
                hotelData.setBookedDates("");
                hotelData.setCapacity(capacity);
                hotelData.setEmail(email);
                hotelData.setHotelAddress(address);
                hotelData.setHotelAdmin(String.valueOf(ID));
                hotelData.setHotelArea(area);
                hotelData.setHotelType(type);
                hotelData.setPhone(phoneNum);
                hotelData.setStatus("PENDING");

                enterpriseController.insertHotelData(hotelData);

                //Create WorkRequest
                WorkRequest wr = new WorkRequest();
                wr.setID(workRequestController.getAllWorkRequestData().size()+1);
                wr.setType("HOTELADMIN_BUSINESSADMIN");
                wr.setFromID(ID);
                wr.setToID(1); //TODO: pass businessAdmin Id
                wr.setStatus("PENDING");
                wr.setEventID(0);
                wr.setEventManagerID(0);
                workRequestController.createWorkRequest(wr);
            } else if(role.equalsIgnoreCase("CATERING ADMIN")){
                //insert in HCT table
                Catering hotelData = new Catering();
                hotelData.setCateringID(enterpriseController.getAllCateringData().size()+1); //TODO: generate
                hotelData.setCateringName(companyName);
                hotelData.setBookedDates("");
                hotelData.setCapacity(capacity);
                hotelData.setEmail(email);
                hotelData.setCateringAddress(address);
                hotelData.setCateringAdmin(String.valueOf(ID));
                hotelData.setCateringArea(area);
                hotelData.setPhone(phoneNum);
                hotelData.setStatus("PENDING");

                enterpriseController.insertCateringData(hotelData);
                
                
                //Create WorkRequest
                WorkRequest wr = new WorkRequest();
                wr.setID(workRequestController.getAllWorkRequestData().size()+1);
                wr.setType("CATERINGADMIN_BUSINESSADMIN");
                wr.setFromID(ID);
                wr.setToID(1); //TODO: pass businessAdmin Id
                wr.setStatus("PENDING");
                wr.setEventID(0);
                wr.setEventManagerID(0);
                workRequestController.createWorkRequest(wr);
            } else if(role.equalsIgnoreCase("TRAVEL AGENT ADMIN")){
                //insert in HCT table
                TravelAgent hotelData = new TravelAgent();
                hotelData.setTravelAgentID(enterpriseController.getAllTravelData().size()+1); //TODO: generate
                hotelData.setTravelAgentName(companyName);
                hotelData.setBookedDates("");
                hotelData.setCapacity(capacity);
                hotelData.setEmail(email);
                hotelData.setTravelAgentAddress(address);
                hotelData.setTravelAgentAdmin(String.valueOf(ID));
                hotelData.setTravelAgentArea(area);
                hotelData.setPhone(phoneNum);
                hotelData.setStatus("PENDING");

                enterpriseController.insertTravelData(hotelData);
                
                
                //Create WorkRequest
                WorkRequest wr = new WorkRequest();
                wr.setID(workRequestController.getAllWorkRequestData().size()+1);
                wr.setType("TRAVELADMIN_BUSINESSADMIN");
                wr.setFromID(ID);
                wr.setToID(1); //TODO: pass businessAdmin Id
                wr.setStatus("PENDING");
                wr.setEventID(0);
                wr.setEventManagerID(0);
                workRequestController.createWorkRequest(wr);
            }
            




            jNameTextField.setText("");
            jEmailTextField.setText("");
            jPhoneNumberTextField.setText("");
            jUsernameTextField.setText("");
            jPasswordTextField.setText("");
            jConfirmPasswordTextField.setText("");
            jPhotoLabel.setIcon(null);
            jPostalCodeTextField.setText("");
            jAddress.setText("");
            jType.setText("");
            jCapacity.setText("");
            jCompanyName.setText("");
            jArea.setText("");
            disableAdditionalFields();
            } catch (SQLException ex) {
                Logger.getLogger(RegisterJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jRegisterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.maple.resources.TextField jAddress;
    private javax.swing.JLabel jAddressLabel;
    private com.maple.resources.TextField jArea;
    private javax.swing.JLabel jAreaLabel;
    private com.maple.resources.TextField jCapacity;
    private javax.swing.JLabel jCapacityLabel;
    private com.maple.resources.TextField jCompanyName;
    private javax.swing.JLabel jCompanyNameLabel;
    private com.maple.resources.TextField jConfirmPasswordTextField;
    private com.maple.resources.TextField jEmailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.maple.resources.TextField jNameTextField;
    private com.maple.resources.TextField jPasswordTextField;
    private com.maple.resources.TextField jPhoneNumberTextField;
    private javax.swing.JLabel jPhotoLabel;
    private com.maple.resources.TextField jPostalCodeTextField;
    private javax.swing.JComboBox<String> jRegisterAsComboBox;
    private com.maple.resources.Button jRegisterBtn;
    private com.maple.resources.TextField jType;
    private javax.swing.JLabel jTypeLabel;
    private com.maple.resources.Button jUploadBtn;
    private com.maple.resources.TextField jUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
