/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.maple.frontend;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author deva
 */
public class UserLeftPanelOptions extends javax.swing.JPanel {

    /**
     * Creates new form UserLeftPanelOptions
     */
    JPanel rightJPanel;
    JPanel leftJPanel;
    public UserLeftPanelOptions(JPanel leftJPanel, JPanel rightJPanel) {
        this.rightJPanel = rightJPanel;
        this.leftJPanel = leftJPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        viewPublicBtn1 = new javax.swing.JButton();

        viewBtn.setText("View My Events");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        createBtn.setText("Create Event");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        viewPublicBtn1.setText("View Public Events");
        viewPublicBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPublicBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(viewPublicBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(313, Short.MAX_VALUE)
                    .addComponent(viewPublicBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(190, 190, 190)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        UserViewMyEvent userViewMyEventRightPanel = new UserViewMyEvent(rightJPanel);
        rightJPanel.add("userViewMyEventRightPanel", userViewMyEventRightPanel);
        CardLayout rightLayout = (CardLayout)rightJPanel.getLayout();
        rightLayout.next(rightJPanel);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        UserCreateEvent userCreateRightPanel = new UserCreateEvent(rightJPanel);
        rightJPanel.add("userCreateRightPanel", userCreateRightPanel);
        CardLayout rightLayout = (CardLayout)rightJPanel.getLayout();
        rightLayout.next(rightJPanel);
    }//GEN-LAST:event_createBtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        HomeJPanel homeScreen = new HomeJPanel(rightJPanel);
        rightJPanel.add("homeScreen", homeScreen);
        CardLayout rightLayout = (CardLayout)rightJPanel.getLayout();
        rightLayout.next(rightJPanel);
        
         //reset left panel
        leftJPanel.remove(this);
        CardLayout layout2 = (CardLayout) leftJPanel.getLayout();
        layout2.previous(leftJPanel);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void viewPublicBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPublicBtn1ActionPerformed
        // TODO add your handling code here:
        UserViewPublicEvents userViewPublicRightPanel = new UserViewPublicEvents(rightJPanel);
        rightJPanel.add("userViewMyEventRightPanel", userViewPublicRightPanel);
        CardLayout rightLayout = (CardLayout)rightJPanel.getLayout();
        rightLayout.next(rightJPanel);
    }//GEN-LAST:event_viewPublicBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton viewPublicBtn1;
    // End of variables declaration//GEN-END:variables
}
